// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdlEVfQn7kaHHqK50sbnQ36bLcrOlYkcY',
    appId: '1:994562712503:web:0508749a99f56a5bbefe32',
    messagingSenderId: '994562712503',
    projectId: 'quizzing-5ad54',
    authDomain: 'quizzing-5ad54.firebaseapp.com',
    storageBucket: 'quizzing-5ad54.firebasestorage.app',
    measurementId: 'G-Y29MKD9H10',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASU158pSLW9AIIIMOoX4Horbm0bAVu_Nc',
    appId: '1:994562712503:android:46f342724a23be1abefe32',
    messagingSenderId: '994562712503',
    projectId: 'quizzing-5ad54',
    storageBucket: 'quizzing-5ad54.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPVci1w-2fiXkQ2UggU9L2LNj7rc8gjPQ',
    appId: '1:994562712503:ios:290057183b22c414befe32',
    messagingSenderId: '994562712503',
    projectId: 'quizzing-5ad54',
    storageBucket: 'quizzing-5ad54.firebasestorage.app',
    iosBundleId: 'com.example.quizzing',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPVci1w-2fiXkQ2UggU9L2LNj7rc8gjPQ',
    appId: '1:994562712503:ios:290057183b22c414befe32',
    messagingSenderId: '994562712503',
    projectId: 'quizzing-5ad54',
    storageBucket: 'quizzing-5ad54.firebasestorage.app',
    iosBundleId: 'com.example.quizzing',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDdlEVfQn7kaHHqK50sbnQ36bLcrOlYkcY',
    appId: '1:994562712503:web:6162bb0d134927a3befe32',
    messagingSenderId: '994562712503',
    projectId: 'quizzing-5ad54',
    authDomain: 'quizzing-5ad54.firebaseapp.com',
    storageBucket: 'quizzing-5ad54.firebasestorage.app',
    measurementId: 'G-X03EMK8F9D',
  );
}
